export default {
  GET_CUSTOMER_DATA: 'GET_CUSTOMER_DATA',
  GET_CUSTOMER_DATA_SUCESS: 'GET_CUSTOMER_DATA_SUCESS',
  GET_CUSTOMER_DATA_FAIL: 'GET_CUSTOMER_DATA_FAIL',
  GET_CUSTOMER_DATA_LOADING: 'GET_CUSTOMER_DATA_LOADING'
}